export enum ConfigCodeEnum {
	DEFAULT_DATE_FORMAT = "DEFAULT_DATE_FORMAT",
	DEFAULT_DATETIME_FORMAT = "DEFAULT_DATETIME_FORMAT",
	CURRENCY_CODE = "CURRENCY_CODE",
	ROUND_OFF_REQUIRED = "ROUND_OFF_REQUIRED",
	DISPLAY_CURRENCY_SYMBOL = "DISPLAY_CURRENCY_SYMBOL",
	AMOUNT_FORMATTING_REQUIRED = "AMOUNT_FORMATTING_REQUIRED",
	RESCHEDULE_ALLOWED = "RESCHEDULE_ALLOWED",
	COUNTRY_CODE = "COUNTRY_CODE",
	CONFIDENCE_SCORE = "CONFIDENCE_SCORE",
	FETCH_BLOG_COUNT = "FETCH_BLOG_COUNT"
}

export enum RequestFromEnum {
	BACKOFFICE = "BACKOFFICE",
	APP = "APP"
}

export enum CashierStatusEnum {
	INITIATED = "INITIATED",
	FAILED = "FAILED",
	DONE = "DONE",
	PENDING = "PENDING"
}

export enum DocumentTypeEnum {
	LEASE = "LEASE",
	UTILITY = "UTILITY"
}

export enum UserTypeEnum {
	NEW_USER = "NEW_USER",
	EXISTING_USER = "EXISTING_USER"
}
