export class Response {
	errorMessage: string;
	errorCode: number;
	constructor(code, message) {
		this.errorCode = code;
		this.errorMessage = message;
	}
}

export const ResponseData = {
	SUCCESS: new Response(0, "Success"),
	DATABASE_ERROR: new Response(80001, "Database error"),
	COLLECTION_IMAGE_UPLOAD_ERROR: new Response(80002, "Collection image upload error"),
	NFT_SALE_IN_PROGRESS: new Response(80003, "Nft sale already in progress"),
	DATA_NOT_FOUND: new Response(10101, "Data Not Found."),
	INVALID_NFT_STATUS: new Response(80004, "Invalid nft status"),
	NFT_NOT_AVAILABE_FOR_SALE: new Response(80005, "NFT not availabe for sale"),
	CURRENCY_DATA_NOT_FOUND: new Response(80006, "Currency data not available"),
	NOT_VALID_TRANSACTION: new Response(80007, "Not valid transaction"),
	INVALID_REQUEST_FORMAT: new Response(80008, "Invalid request format"),
	INVALID_TXN_ID: new Response(80009, "Invalid transaction id found from event"),
	RUMBLE_TRANSACTION_FAILED: new Response(80010, "Rumble transaction failed"),
	CRYSTAL_DEBIT_ERROR: new Response(80011, "Crystal debit error"),
	INVALID_EXCHANGE_TYPE: new Response(80012, "Invalid exchange type found"),
	INVALID_CATEGORY: new Response(80013, "Invalid category"),
	INVALID_COUNT_VALUE: new Response(80014, "Invalid count value"),
	INVALID_PRICE_VALUE: new Response(80015, "Invalid price value"),
	INVALID_COLLECTION_ID: new Response(80016, "Invalid collection id"),
	INVALID_INVENTORY_ID: new Response(80017, "Invalid inventory id"),
	INVALID_FILE_TYPE: new Response(80018, "Invalid input file type"),
	INVALID_REQUEST_ID: new Response(80019, "Invalid request id"),
	RESPONSE_NOT_MATCH: new Response(80020, "Response not match csv file"),
	ERROR_WHILE_READING_FILE: new Response(80021, "Error in reading file"),
	INVALID_FILE_URL: new Response(80022, "Invalid input file url"),
	HEADERS_NOT_MATCH: new Response(80023, "Invalid headers in csv"),
	ATTRIBUTES_NOT_MATCH: new Response(80024, "Attributes not matching"),
	NO_NETWORK_AVAILABLE: new Response(80025, "No network available"),
	INVALID_NETWORK_ID: new Response(80026, "Invalid network id"),
	NFT_ATTRIBUTE_NOT_FOUND: new Response(80027, "Attribute not found in csv"),
	NFT_COUNT_EXCEEDS: new Response(80028, "Nft count must be less than or equals to 500"),
	EOF_NOT_FOUND: new Response(80029, "EOF not found"),
	ERROR_WHILE_UPDATING_FILE: new Response(80030, "Error in updating attributes."),
	INVALID_ID_FOUND: new Response(80031, "Invalid Id found."),
	INVALID_TXN_SUPPLY_TYPE: new Response(80032, "Invalid Txn Supply Type."),
	ERROR_WHILE_UPDATING_NEW_CURRENCY_DATA: new Response(80033, "Error while updating new currency data."),
	WALLET_ADDRESS_NOT_FOUND: new Response(80034, "Please register your blocto wallet first."),
	USER_NOT_MAPPED_TO_THIS_WALLET: new Response(80035, "User not mapped to this wallet address."),
	TXN_NOT_FOUND: new Response(80036, "Transaction Not Found"),
	TOKEN_TRANSACTION_FAILED: new Response(80037, "Token transaction failed"),
	TOKEN_TRANSACTION_EXIST: new Response(80038, "Token transaction already exist"),
	INVALID_PE_TXN_ID: new Response(80039, "Invalid peTxnId."),
	CASHIER_RESPONSE_ERROR: new Response(80040, "Cashier response error"),

	UNKNOWN_ERROR_OCCURRED: new Response(1, "Something went wrong ! Please try after some time."),
	UNKNOWN_EXCEPTION: new Response(70001, "Unknown Error Occurred, Please Try Again."),
	INVALID_PARAMETER: new Response(70002, "No Parameter Found For Update."),
	REQUIRED_VALIDATION_ERROR: new Response(70003, "Please Provide Valid ##@@##"),
	LENGTH_VALIDATION_ERROR: new Response(70004, "Invalid Length Found For ##@@##"),
	REGEX_VALIDATION_ERROR: new Response(70005, "Invalid Format Found For ##@@##"),
	DATE_VALIDATION_ERROR: new Response(70006, "Please Provide Valid Date For ##@@##"),
	INVALID_JSON: new Response(70007, "Invalid JSON Found."),
	URL_NOT_FOUND_ERROR_CODE: new Response(70008, "Requested Url Not Found"),
	INVALID_TOKEN: new Response(7009, "Please Provide Valid Token"),
	INVALID_RESPONSE: new Response(70010, "Invalid Response Found From BackOffice"),
	INVALID_RESPONSE_COMM: new Response(70011, "Invalid Response Found From Communication"),
	VALIDATION_ERROR: new Response(70012, "Invalid Validation Structure Found."),
	INVALID_RESPONSE_SME: new Response(70013, "Invalid Response Found From SME"),

	INVALID_CLIENT_TOKENS: new Response(799999, "Invalid Client Token"),

	ERROR_IN_DECRYPTING_TOKEN: new Response(70014, "Error In Decrypting Token"),

	/********** Validation Codes 10001-10100 *******************/

	VALIDATION_STRUCTURE_MISSING: new Response(10003, "No Validation Structure Found."),
	ERROR_FROM_UCM: new Response(10013, "Error in getting login details from UCM"),

	/********** Common Management Codes 10101-10200 *******************/
	INVALID_CLIENT: new Response(10102, "Invalid Client Found."),
	IP_ADDRESS_MISSING: new Response(10103, "Please Provide Valid System IP Address."),
	INVALID_CURRENCY: new Response(10104, "Invalid Currency Found."),
	DUPLICATE_CONFIG_CODE: new Response(10105, "Duplicate Config Code Found In Request."),
	INVALID_MOBILE_NO: new Response(10106, "Please Provide Valid Mobile No"),
	INVALID_EMAIL: new Response(10107, "Please Provide Valid Email"),
	INVALID_COMM_CONTENT_CODE: new Response(10108, "Please Provide Valid Communication Contents"),
	INVALID_EMAIL_SUBJECT: new Response(10109, "Please Provide Valid Email Subject"),
	INVALID_STATE_FOUND: new Response(10110, "Please Provide Valid State."),
	INVALID_CONFIG_VALUE: new Response(10111, "Invalid Configuration Value Found."),
	INVALID_LIMIT_AND_OFFSET: new Response(10112, "Please Provide Valid Pagination Limit And Offset."),
	INVALID_CLIENT_CODE: new Response(10113, "Invalid Client Code Found."),
	INVALID_CLIENT_PWD: new Response(10114, "Invalid Client Password Found."),
	/********** Channel Management Codes 10201-10250 *******************/
	INVALID_CHANNEL_FOUND: new Response(10201, "Invalid Channel Found."),
	EXISTS_SYSTEM_CHANNEL_ID: new Response(10202, "System Channel Id Already Exists."),
	EXISTS_SYSTEM_CHANNEL_NAME: new Response(10203, "System Channel Name Already Exists"),
	DOMAIN_MAPPING_FAILED: new Response(10204, "Channel Mapping Failed for User"),
	INVALID_EMAIL_REGEX: new Response(10205, "Please Provide Valid Email Regex."),
	INVALID_MOBILE_REGEX: new Response(10206, "Please Provide Valid Mobile Regex."),
	INVALID_ZIP_REGEX: new Response(10207, "Please Provide Valid Zip Code Regex."),
	OTP_LIMIT_EXCEEDED_CODE: new Response(10208, "Maximum Limit Reached For Otp. Please Try Again After "),

	/********** Criteria Management Codes 10251-10300 *******************/
	CRITERIA_NOT_FOUND: new Response(10251, "No Criteria Found."),
	INVALID_MOBILE_CODE: new Response(10106, "Please Provide Valid Mobile Code"),

	/********** User Management Codes 10301-10350 *******************/
	INVALID_USER_FOUND: new Response(10301, "This User Is Not Registered Here."),
	EMAIL_ALREADY_EXIST: new Response(10302, "Email Already Exist."),
	MOBILE_ALREADY_EXIST: new Response(10303, "Mobile Already Exist."),
	USERNAME_ALREADY_EXIST: new Response(10304, "Username Already Exist."),
	USER_ALREADY_EXIST: new Response(10305, "User Already Exist."),
	INVALID_COUNTRY_FOUND: new Response(10306, "Invalid Country Found."),
	EITHER_USERNAME_PASSWORD_INVALID: new Response(406, "Either username or password is invalid"),
	INVALID_USERNAME: new Response(10308, "Please enter valid Mobile/Email"),
	COUNTRY_NOT_MAPPED_WITH_CURRENCY: new Response(10309, "Country Not Mapped With Any Currency."),
	INVALID_BANK_DETAIL_FIELDS: new Response(10310, "Invalid Bank Detail Fields."),
	PROVIDE_EITHER_EMAIL_ID_OR_MOBILBE_NUMBER: new Response(10311, "Please Provide Either Email Id Or Mobile Number."),

	/********** Alias Management Codes 10351-10400 *******************/
	ALREADY_EXIST_ALIAS: new Response(10351, "Alias Already Exist."),
	INVALID_SYSTEM_ALIAS: new Response(10352, "Invalid System / Alias / Channel Found."),
	INVALID_ALIAS: new Response(10353, "Invalid  Alias Found."),
	NO_ACTIVE_ALIAS: new Response(10354, "No Active Alias Found."),

	/********** Business Management Codes 10401-10450 *******************/
	INVALID_BUSINESS: new Response(10401, "Please Provide Valid Business."),
	BUSINESS_EMAIL_ALREADY_REGISTERED: new Response(10402, "Business Already Registered With Requested Email Id."),
	BUSINESS_MOBILE_ALREADY_REGISTERED: new Response(10403, "Business Already Registered With Requested Mobile Number."),
	BUSINESS_ALREADY_REGISTERED: new Response(10404, "Business Already Registered."),
	BUSINESS_CODE_ALREADY_REGISTERED: new Response(10405, "Business Already Registered With Requested Code."),

	/********** Consumer Management Codes 10451-10500 *******************/
	INVALID_SECURITY_QUESTION: new Response(10451, "Please Provide Valid Security Questions."),
	CONSUMER_ALREADY_EXIST: new Response(10452, "Consumer Already Exist."),
	OTP_VERFICATION_FAILED: new Response(10453, "Otp Verification Failed."),
	OTP_EXPIRED: new Response(10454, "Entered OTP is Expired. Please Try Again."),
	INVALID_DATE: new Response(10455, "Please Provide Valid Date."),
	INVALID_SYSTEM_API_URLS: new Response(10456, "Please Provide Valid System API Urls."),
	INVALID_URL_FOR_WEAVER_CONSUMER_REGISTER: new Response(10457, "Please Provide Valid Consumer Register Url."),
	INVALID_URL_FOR_WEAVER_CONSUMER_LOGIN: new Response(10458, "Please Provide Valid Consumer Login Url."),
	INVALID_RESPONSE_RECEIVED_FROM_WEAVER: new Response(10459, "Something went wrong, please try again later."),
	INVALID_URL_FOR_CONSUMER_PROFILE: new Response(10460, "Please Provide Valid Consumer Profile Url."),
	EMAIL_VALIDATION_FROM_FACEBOOK_FAILED: new Response(10493, "Your Facebook Account Is Not Linked To Any Email Id."),
	DOC_PATH_NOT_VALID: new Response(10461, "Please Provide Valid Doc Path."),
	ERROR_IN_IMAGE_UPLOAD: new Response(10462, "Error In Image Upload."),
	NO_ACTIVE_DOCTYPE_EXIST: new Response(10463, "No Active Doctype Exist."),

	INVALID_FILE_SIZE: new Response(10464, "Uploaded File Size Should Be Less Than "),
	INVALID_SECURITY_QUESTION_COUNT: new Response(10465, "Please Provide Atleast "),
	INVALID_URL_FOR_WEAVER_CHECK_LOGIN: new Response(10466, "Please Provide Valid Check Login status Url."),
	INVALID_CONSUMER_ID: new Response(10467, "Please Provide Valid Consumer Id In Headers."),
	INVALID_CONSUMER_TOKEN: new Response(10468, "Please Provide Valid Consumer Token In Headers."),
	DIFFERENT_REQUEST_CONSUMER_AND_LOGGED_IN_CONSUMER: new Response(
		10469,
		"Requested Consumer And Logged In Consumer Are Different."
	),
	NO_VERIFICATION_DETAIL_FOUND: new Response(10470, "No Verification Detail Found For Consumer."),
	USER_NOT_MAPPED_WITH_SECURITY_QUESTIONS: new Response(10471, "User Not Mapped With Requested Security Questions."),
	SECURITY_QUESTION_WRONG_ATTEMPT_LIMIT_REACHED: new Response(10472, "Security Question Wrong Attempt Limit Reached."),
	WRONG_ANSWER_FOR_SECURITY_QUESTION: new Response(10473, "Please Provide Correct Answer For Security Questions."),
	INVALID_URL_FOR_WEAVER_CHANGE_PASSWORD: new Response(10474, "Please Provide Valid Change Password Url."),
	USER_SECURITY_QUESTION_EXISTS: new Response(10475, "User's Security Question Already Added."),
	INVALID_EMAIL_VERIFICATION_LINK: new Response(10476, "Invalid EMail Verification Link."),
	VERIFICATION_EXPIRED: new Response(10477, "Verification Link Expired."),
	INVALID_EMAIL_VERIFICATION_DATA: new Response(10478, "No Data Found Email Verification."),
	EMAIL_ALREADY_VERIFIED: new Response(10479, "Email Already Verified."),
	DOC_SUBMITTED_CONFIG_NO: new Response(10480, "Document Submission Config is No."),
	INVALID_OLD_PASSWORD: new Response(10481, "Old Password is Incorrect."),

	EMAIL_UPDATE_FAILED: new Response(10482, "Email Address Change Was Unsuccessful"),
	PASSWORD_UPDATE_FAILED: new Response(10483, "Password Change Was Unsuccessful"),
	RSA_DOC_NOT_FOUND: new Response(10484, "RSA Documents Not Found"),
	OTP_SENT: new Response(10486, "OTP Sent Successfully"),
	INVALID_OTP: new Response(10487, "Invalid OTP Found"),
	MOBILE_UPDATE_FAILED: new Response(10488, "Mobile Number Change Was Unsuccessful"),
	UPDATE_REQUEST_NOT_FOUND: new Response(10489, "Consumer Profile Update Request Not Found"),
	OTP_DATA_NOT_FOUND: new Response(10490, "Otp Data Not Found"),
	INVALID_CONSUMER: new Response(10491, "This User Is Not Registered Here."),
	INVALID_PROFILE_STATUS: new Response(10491, "Invalid Profile Status Found."),
	ALREADY_UPDATE: new Response(10492, "Already Updated"),

	REQUEST_IN_PROGRESS: new Response(10494, "Request Already In Progress."),
	CONSUMER_INFO_NOT_FOUND: new Response(10495, "Consumer Basic Information Not Found."),
	INVALID_CONFIG_STATUS: new Response(10496, "Invalid Status Found In Configurations."),
	INVALID_DOC: new Response(10497, "Please Provide Valid Document"),
	INVALID_URL_FOR_WEAVER_HEADER_INFO: new Response(10498, "Please Provide Valid Header Info URL."),
	INVALID_URL_FOR_WEAVER_CONSUMER_PROFILE: new Response(10499, "Please Provide Valid Consumer Profile URL."),
	EXISTING_SEC_QUESTION_NOT_FOUND: new Response(10500, "Consumer's Existing Security Questions Not Found For Update."),
	EXISTS_SEC_QUESTION: new Response(10501, "Security Question Already Added."),

	USERNAME_REQUIRED: new Response(10502, "Username Is Required For Other Types"),
	DURATION_REQUIRED: new Response(10503, "Duration Is Required For Other Types"),

	USERNAME_OR_DURATION_REQUIRED: new Response(10504, "Atleast One of Username or Duration Is Required For Other Types"),
	INVALID_TYPE: new Response(10505, "Invalid type"),
	VRIFICATION_REQUEST_ALREADY_ASSIGN: new Response(10506, "Verification Request Already Assigned"),
	VRIFICATION_REQUEST_ALREADY_NOT_ASSIGN: new Response(10507, "Verification Request Already Not Assign To a User"),
	VERIFICATION_REQUEST_ASSIGN: new Response(10508, "Verification Request Successfuly Assigned"),
	VERIFICATION_REQUEST_REASSIGN: new Response(10509, "Verification Request Successfuly Reassigned"),
	VERIFICATION_REQUEST_ALREADY_ASSIGNED: new Response(10511, "Request Already Assigned To Requested User."),
	REQUEST_CAN_NOT_ASSIGN_TO_LOGGED_IN_USER: new Response(10510, "Request Can Not Assigned to Logged In User"),
	NO_DOC_EXISTS: new Response(10512, "No Document Exist"),
	REMARK_NECESSARY_WHILE_REJECTING: new Response(10513, "Please Provide Remark For Rejecting Document."),
	NOT_ALLOWED: new Response(10514, "You Are Not Allowed To Perform This Action."),
	DOCUMENT_ACTIVATE_CODE: new Response(10515, "Document Is Already Active , Rejected or Expired."),
	DOCUMENT_REJECTED_CODE: new Response(10516, "Document Is Already Rejected or Expired."),
	NO_DOCUMENT_EXIST_FOR_CONSUMER: new Response(10517, "No Document Exist For Consumer."),
	VERIFICATION_PENDING_EMAIL_MOBILE_SECURITY_QUESTION: new Response(
		10518,
		"Verification Pending For Consumer Email, Mobile, Name or Security Question."
	),
	SOME_DOCUMENT_VERIFICATION_NOT_DONE: new Response(
		10519,
		"Some Consumer Documents Are Not Verified Yet,either Activate Them Or Reject Them."
	),
	ATLEAST_ONE_ACTIVE_DOCUMENT_FOR_EACH_DOCTYPE: new Response(
		10520,
		"Consumer Does Not Have a Active Document For All Active Doctypes"
	),
	CONSUMER_NOT_ALLOWED: new Response(10521, " Not Allowed As Per Status."),
	UNSUCCESSFUL_OTP_ATTEMPT: new Response(10522, "You have exceeded your number of attempts, please try again later."),
	INVALID_PRIMARY_ID: new Response(10523, "Please Provide Valid Consumer Primary Id."),
	ADDRESS_UPDATE_FAILED: new Response(10524, "Consumer Address Update Failed."),
	COUNTER_NOT_FOUND: new Response(10525, "Consumer Counter Data Not Found"),
	PROFILE_STATUS_ALREADY_SAME_AS_REQUESTED: new Response(10526, "Consumer Profile Status Already Same As Requested"),
	DOCUMENT_PENDING_VALIDAITY_EXPIRE: new Response(10527, "Consumer's Document Upload Pending Validity Expired."),
	LOGIN_EMAIL_NOT_VERIFIED: new Response(10528, "Email Not Verified For Successful Login."),
	INVALID_ANSWER_LENGTH: new Response(10529, "Please Provide Valid Security Question's Answer Length."),
	INVALID_ANSWER_FORMAT: new Response(10530, "Please Provide Valid Security Question's Answer Format."),
	ONE_CHANNEL_ID_REQUIRED: new Response(10531, "Only Provide Either ChannelId or SystemDoaminId"),
	VERIFICATION_PENDING_REQUIRED: new Response(
		10532,
		"Consumer Profile Status Has To Be On Verification Pending for this Action."
	),
	LAST_REQUEST_PROCESSED: new Response(10533, "Consumer's Last Request was Processed."),
	CHANGENAME_UPDATE_FAILED: new Response(10534, "Consumer's Name Change Was Unsuccessful"),
	INVALID_STATUS: new Response(10535, "Please Provide Valid Status."),
	PROFILE_UPDATE_LIMIT: new Response(10536, "Profile Update Request Count Reached."),
	NO_ACTIVE_DOC_IN_ADDRESS_PROOF: new Response(10537, "Consumer Does Not Have a Active Document For Address Proof."),
	PROFILE_ACTIVE_FOR_INACTIVE: new Response(10538, "Consumer Profile Has To Be Active For Inactivating Its Profile."),
	CONSUMER_DOC_UPLOAD_PENDING: new Response(10539, "Consumer Needs To Upload Documents For Profile Activation."),
	CONSUMER_STATUS_UPDATE_NOT_ALLOWED: new Response(10540, "Please update Rsa Id first."),
	LAST_MESSAGE: new Response(20000, "Last Message So every time we dont need to change termination."),
	REQUESTED_RSA_ID_ALREADY_EXIST: new Response(10541, "Requested Rsa Id Already Exist."),
	CONSUMER_UNDER_AGE: new Response(10542, "Invalid Age - Must Be At Least 18 Years."),
	REQUESTED_MOBILE_NUMBER_SAME_AS_CONSUMER_OLD_MOBILE_NUMBER: new Response(
		10543,
		"Requested Mobile Number Same As Consumer's Old Mobile Number."
	),
	CONSUMER_ADDRESS_UPDATE_PENDING: new Response(10544, "Please Verify Address Update Request First."),
	UPLOAD_DOC_BEFORE_ADDRESS_UPDATE: new Response(10545, "Please upload documents before changing address"),
	EXPIRY_NOT_PRESENT_FOR_CHANGE_TYPE: new Response(10546, "No Expiry Days Present For Requested Change Type."),
	INVALID_CITY_FOUND: new Response(10547, "Invalid City Found"),
	INVALID_ZIP_CODE: new Response(10548, "Please Provide Valid Pin Code."),
	BLOCKED_RSA_ID: new Response(10549, "Registration not allowed for given RSA ID."),
	INVALID_SYSTEM_CONSUMER_ID_OR_USER_NAME: new Response(
		10550,
		"Please Provide Either System Consumer Id Or User Name or Mobile Number."
	),
	ONLY_SYSTEM_CONSUMER_ID_OR_USER_NAME: new Response(
		10551,
		"Only Provide Either System Consumer Id or User Name or Mobile Number."
	),
	CONSUMER_REG_REQ_STATUS_NOT_FOUND: new Response(10552, "No Data Present For This Request Id."),
	REQUEST_ALREADY_PROCESSED: new Response(10553, "Request Already Proccessed."),
	INVALID_REQUEST_TYPE: new Response(10554, "Please Provide Valide Request Type."),
	INVALID_REQUESTED_AND_OTP_EMAIL: new Response(
		10555,
		"Email Id For Receiving OTP And In Requested Identity Info Details Have To Be Same."
	),
	INVALID_REQUESTED_AND_OTP_MOBILE: new Response(
		10556,
		"Mobile Number For Receiving OTP And In Requested Identity Info Details Have To Be Same."
	),
	INVALID_REGISTRATION_PEP: new Response(10557, "Please Provide Valid Registration Politically Exposed Person Status"),
	INVALID_REQUEST_FOR_REG_OTP_DATA: new Response(10558, "Invalid Request For Reg Otp Data."),
	INVALID_IMAGE_OR_DOC_PATH: new Response(10559, "Please Provide Valid image or Document Path."),
	INVALID_DATE_OF_BIRTH: new Response(10560, "Please Provide Valid Date Of Birth."),
	REPORT_CHUNK_SIZE_EXCEED: new Response(10561, "Report Chunk Size is Grater than Report Max Size."),
	DUPLICATE_PRIMARY_ID: new Response(10562, "Consumer Already Exist With This Primary Id."),
	INVALID_MPIN: new Response(10563, "Invalid MPIN."),
	MPIN_ALREADY_EXIST: new Response(10564, "MPIN Alerady Exits."),
	CONSUMER_DEVICE_MAPPING_NOT_FOUND: new Response(10565, "Consumer Device Mapping Not Found."),
	REQUESTED_ACCOUNT_STATUS_SAME_AS_CONSUMER_OLD_ACCOUNT_STATUS: new Response(
		10566,
		"Requested Account Status Same As Consumer's Old Account Status."
	),
	CONSUMER_BLOCKED_CONTACT_ADMINISTRATOR_MESSAGE: new Response(
		10567,
		"Consumer is blocked. Please contact The Administrator."
	),
	CONSUMER_ID_ALREADY_UNBLOCKED_ERROR_MESSAGE: new Response(
		10568,
		"This Operation Is Not Allowed, Requested User Already Unblocked."
	),
	INVALID_BLOCK_STATUS_ERROR_MESSAGE: new Response(10569, "Please Provide Valid Block / Unblock Status."),
	EXCEED_CHANGE_PASSWORD_LIMIT_ERROR_MESSAGE: new Response(
		10570,
		"You Are Exceed Your Change Password Attempt Please Try Again After Sometime."
	),
	INVALID_RSA_ID: new Response(10571, "Please Provide Valid Consumer RSA Id."),
	APP_TYPE_OR_LOGIN_DEVICE_MISSING: new Response(10572, "AppType and LoginDevice Missing"),
	REQUESTED_PRIMARY_ID_SAME_AS_CONSUMER_OLD_PRIMARY_ID: new Response(
		10573,
		"Requested Priamry Id Same As Consumer's Old Primary Id."
	),
	REQUESTED_PRIMARY_ID_ALREADY_EXIST: new Response(10574, "Requested Primary Id Already Exist."),
	PASSWORD_MUST_NOT_BE_SAME_AS_OLD_PASSWORD: new Response(10575, "Password Must Not Be Same As Old Password."),
	SESSION_EXPIRED_LOGIN_AGAIN: new Response(10576, "Session Expired, Please Login Again"),
	INVALID_USER_ID: new Response(10577, "Please Provide Valid User Id In Headers."),
	INVALID_USER_TOKEN: new Response(10578, "Please Provide Valid User Token In Headers."),
	INCORRECT_USERNAME_PASSWORD: new Response(10579, "Incorrect Username or Password."),
	INVALID_RESPONSE_RECEIVED_FROM_ACCOUNTING: new Response(10459, "Something went wrong, please try again later."),
	MOBILE_ALREADY_VERIFIED: new Response(10580, "Mobile Already Verified."),
	FILE_NOT_FOUND: new Response(10581, "Image File Not Found."),
	PASSWORD_NOT_MATCHED: new Response(10582, "New Password And Confirm Password Does Not Matched."),
	PASSWORD_CHANGED_SUCCESSFULLY: new Response(10583, "Password Changed Successfully."),
	ERROR_IN_FILE_UPLOAD: new Response(10584, "Error in file Upload, Please Try After Some Time."),
	MAX_FILE_SIZE_EXCEEDED: new Response(10585, "Max File Upload Size Exceeded."),
	INVALID_DURATION: new Response(10586, "Please Provide Valid Time Duration."),
	REQUESTED_RSA_ID_SAME_AS_CONSUMER_OLD_RSA_ID: new Response(10588, "Requested Rsa Id Same As Consumer's Old Rsa Id."),
	INVALID_CONFIGURATION: new Response(10587, "Please Provide Valid Configurations."),
	ALIAS_NAME_ALREADY_EXIST: new Response(10589, "Alias Name Already Exist."),

	CATEGORY_ALREADY_EXISTS: new Response(800003, "Category Already Exists"),
	EXISTS_CHANNEL_ID: new Response(80004, "Channel Already Exist."),
	EXISTS_CHANNEL_NAME: new Response(80005, "Channel Name Already Exist."),
	ERROR_IN_FILE_UPLOAD_TO_IPFS: new Response(10584, "Error in Uploading file to IPFS, Please Try After Some Time."),
	ERROR_IN_MINTING: new Response(800005, "Error in minting"),
	ERROR_IN_LISTING: new Response(800078, "Error in Listing"),
	NFT_IMAGE_NOT_AVAILABLE: new Response(80006, "IPFS image not available to mint"),
	MINTED_NFT_NOT_FOUND: new Response(80008, "Minted Nft not available"),
	INVALID_ACTION_TYPE: new Response(80008, "Invalid Action Type"),
	INVALID_NFT_ID: new Response(80008, "Invalid NFT Id"),
	INVALID_NFT_DATA: new Response(80009, "Invalid NFT Data"),
	NFT_IMAGE_AND_QUANTITY_MISMATCH: new Response(80010, "NFT Image Url's Mismatch with Quantity"),
	NFT_ICON_AND_QUANTITY_MISMATCH: new Response(80011, "NFT Icon Url's Mismatch with Quantity"),

	//CRYR ERRORS
	NO_PLAID_TOKEN_FOUND: new Response(800011, "No plaid token found."),
	INVALID_PLAID_TOKEN: new Response(800012, "Invalid plaid token."),
	INVALID_PAYMENT_TYPE: new Response(800013, "Invalid payment type."),
	INVALID_REFDOC_ID: new Response(800014, "Invalid reference document Id."),
	INVALID_VALIDATION_PROOF_ID: new Response(800015, "Invalid validation proof Id."),
	PACKAGE_ALREADY_EXIST: new Response(800016, "Package already exist."),
	INVALID_REFDOC_TYPE_ID: new Response(800017, "Invalid reference document type Id."),
	SUBSCRIPTION_ALREADY_EXIST: new Response(800018, "User subscription already exist for ref doc type."),
	INVALID_PACKAGE_ID: new Response(800019, "Invalid package Id."),
	REFDOC_NOT_FOUND: new Response(800020, "Refdoc not found."),
	INVALID_PARTICIPANT_REQUEST: new Response(800021, "Invalid participant request."),
	PLAID_ERROR: new Response(800022, "Plaid server error."),
	NO_PLAID_TRANSACTION_FOUND: new Response(800023, "No plaid transaction found."),
	INVALID_PLAID_TXN_ID: new Response(800024, "Invalid transaction Id."),
	REFDOC_SUBSCRIPTION_ALREADY_EXIST: new Response(800025, "User subscription already exist for this ref doc."),
	STRIPE_ERROR: new Response(800026, "Stripe error."),
	CURRENCY_CODE_NOT_FOUND: new Response(800027, "User currency code not found."),
	INVALID_PARTICIPANT_DATA: new Response(800028, "Invalid participant data."),
	INVALID_PAYEE: new Response(800029, "Invalid payee."),
	INVITATION_ALREADY_ACCEPTED: new Response(800030, "Invitation already accepted."),
	NO_SUBSCRIPTION_AVAILABLE: new Response(800031, "Subscription in process."),
	REFDOC_UPDATE_NOT_ALLOWED: new Response(800032, "Reference document update not allowed."),
	REFDOC_FILE__SIZE_TOO_LARGE: new Response(800033, "Reference document size larger than ##@@## MB."),
	INVALID_MASTER_PROOF_ID: new Response(800034, "Invalid master proof id."),
	INVALID_REJECTION_REASON_ID: new Response(800035, "Invalid rejection reason id."),
	INVALID_MONTHLY_PROOF_ID: new Response(800036, "Invalid monthly proof id."),
	EITHER_EMAIL_MOBILE_INVALID: new Response(800037, "Either email or mobile is invalid."),
	EITHER_EMAIL_MOBILE_NOT_FOUND: new Response(800038, "Either email or mobile is not found."),
	INVALID_MASTERPROOF: new Response(800039, "Either master proof is not found or not approved."),
	INVALID_PAYMENT_SCHEDULE: new Response(800040, "Invalid payment schedule."),
	INVALID_BLOG_CATEGORY_ID: new Response(800041, "Invalid blog article category Id."),
	DUPLICATE_PAYMENT_ID: new Response(800042, "Payment id already exist."),
	INVALID_PAYMENT_ID: new Response(800043, "Invalid payment id."),
	INVALID_TRANSACTION_ID: new Response(800044, "Invalid transaction id."),
	MONTHLY_PROOF_INSERTION_ERROR: new Response(800045, "Monthly proof insertion error."),
	REFDOC_NOT_APPROVED: new Response(800046, "Reference document not approved."),
	DISPUTE_ALREADY_RAISED: new Response(800047, "Dispute already raised for this payment type."),
	INVALID_DISPUTE_ID: new Response(800048, "Invalid dispute Id."),
	INVALID_USER_ID_IN_REQUEST: new Response(800049, "Invalid user id."),
	USER_NOT_FOUND: new Response(800050, "User not found."),
	MONTHLY_PROOF_UPLOAD_NOT_ALLOWED_FOR_PLAID: new Response(800051, "Monthly proof upload not allowed for Plaid."),
	INVALID_DISPUTE_TYPE_ID: new Response(800052, "Invalid dispute type id."),
	MONTHLY_PROOF_REQUESTED: new Response(800053, "Monthly proof verification pending for this payment type."),
	DATA_ALREADY_EXIST: new Response(800054, "Lease data already exist."),
	INVITATION_ALREADY_SENT: new Response(800055, "Invitation already sent."),
	NO_ACTIVE_SUBSCRIPTION_FOUND: new Response(800056, "No active subscription found."),
	INVALID_ALIAS_ID: new Response(800057, "Invalid alias id."),
	PACKAGE_AUTO_RENEW_NOT_ALLOWED: new Response(800058, "Package auto renewal not allowed."),
	SUBSCRIPTION_ALREADY_IN_PROCESS: new Response(800059, "Transaction already in processing."),
	PAYMENT_SCHEDULE_NOT_FOUND: new Response(800060, "Payment schedule not found."),
	MASTERPROOF_NOT_FOUND: new Response(800061, "VeriDoc Master Proof not found."),
	INVALID_REFDOC_TYPE: new Response(800062, "Invalid refdoc type."),
	INVALID_TRANSACTION_DATE: new Response(800063, "Invalid transaction date."),
	SUBSCRIPTION_NOT_FOUND: new Response(800064, "Subscription not found for this refdoc."),
	USER_PAYMENT_SCHEDULE_NOT_FOUND: new Response(800065, "User payment schedules not found."),
	FIRST_SUBSCRIPTION_NOT_FOUND: new Response(800066, "First subscription not found for this refdoc.LookBack not allowed."),
	INVALID_FLEX_AGREEMENT_NUMBER: new Response(800067, "Invalid Flex agreement number."),
	INVALID_CHECK_NUMBER: new Response(800068, "Invalid check number."),
	INVALID_MONEY_ORDER_NUMBER: new Response(800069, "Invalid Money Order number."),
	INVALID_VERIFIED_PROOF_ID: new Response(800070, "Invalid Verified Proof Id."),
	MONTHLY_PROOF_IS_REPORTED: new Response(800071, "MonthlyProof is reported."),
	MONTH_IS_REQUIRED: new Response(800072, "Month is required."),
	NO_PLAID_TXNS_FOUND: new Response(800073, "No plaid transactions found."),
	INVALID_MONTH: new Response(800074, "Invalid Month."),
	INVALID_BENIFICIARY_USER_ID: new Response(800075, "Invalid benificiary user id."),
	NO_MERCHANT_NAME: new Response(800076, "Merchant name not present."),
	MONTHLYPROOF_ALREADY_VERIFIED: new Response(800077, "MonthlyProof already verified."),
	MONTH_AND_YEAR_NOT_PROVIDED: new Response(800078, "Payment month and year not provided."),
	INVALID_THUMBNAIL_URL: new Response(800079, "Invalid thumbnail.")
};
