export enum Status {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	TERMINATED = "TERMINATED",
	TERMINATE = "TERMINATE"
}

export enum PaymentStatusEnum {
	PURCHASE_INITIATED = "PURCHASE_INITIATED",
	PAYMENT_DONE = "PAYMENT_DONE",
	PAYMENT_FAILED = "PAYMENT_FAILED"
}

export enum RequestStatusEnum {
	REJECTED = "REJECTED",
	EXPIRED = "EXPIRED",
	REQUESTED = "REQUESTED",
	APPROVED = "APPROVED",
	VERIFICATION_PENDING = "VERIFICATION_PENDING",
	NEW_PARTICIPANT = "NEW_PARTICIPANT"
}

export enum RefdocUserStatusEnum {
	REJECTED = "REJECTED",
	EXPIRED = "EXPIRED",
	REQUESTED = "REQUESTED",
	APPROVED = "APPROVED",
	VERIFICATION_PENDING = "VERIFICATION_PENDING",
	NEW_PARTICIPANT = "NEW_PARTICIPANT",
	INVITATION_PENDING = "INVITATION_PENDING",
	INVITED = "INVITED",
	PARTICIPANT = "PARTICIPANT"
}

export enum ParticipantActionTypeEnum {
	ADD = "ADD",
	UPDATE = "UPDATE"
}

export enum HaveLeaseStatus {
	YES = "YES",
	NO = "NO"
}

export enum LeaseParticipantType {
	SELF = "SELF",
	PAYMENT_REQUEST = "PAYMENT_REQUEST",
	PARTICIPANT = "PARTICIPANT"
}

export enum InviteMethodType {
	MOBILE = "MOBILE",
	EMAIL = "EMAIL"
}

export enum RentPaymentByEnum {
	SELF = "SELF",
	TOGETHER = "TOGETHER",
	OTHER = "OTHER"
}

export enum SubscriptionPaymentTypeEnum {
	SUBSCRIPTION = "SUBSCRIPTION",
	SERVICE = "SERVICE",
	MODIFY_SUBSCRIPTION = "MODIFY_SUBSCRIPTION",
	AUTO_DEBIT_SUBSCRIPTION = "AUTO_DEBIT_SUBSCRIPTION",
	LOOKBACK_SUBSCRIPTION = "LOOKBACK_SUBSCRIPTION"
}

export enum YesNoEnum {
	YES = "YES",
	NO = "NO"
}

export enum RentDetailsStatusEnum {
	PENDING = "PENDING",
	DONE = "DONE",
	NOT_SELECTED = "NOT_SELECTED"
}

export enum InviteeTypeEnum {
	PAYMENT_REQUEST = "PAYMENT_REQUEST",
	PARTICIPANT = "PARTICIPANT"
}

export enum PayeeTypeEnum {
	SELF = "SELF",
	OTHER = "OTHER"
}

export enum ParticipantUserType {
	PRIMARY = "PRIMARY",
	PARTICIPANT = "PARTICIPANT"
}

export enum UserProfileStatusEnum {
	SUBSCRIPTION_PENDING = "SUBSCRIPTION_PENDING",
	REFDOC_PENDING = "REFDOC_PENDING",
	LEASE_DATA_PENDING = "LEASE_DATA_PENDING",
	PLAID_PENDING = "PLAID_PENDING",
	HOME = "HOME",
	INVITED_PLAID_PENDING = "INVITED_PLAID_PENDING",
	INVITED_HOME = "INVITED_HOME",
	INVITED_LEASE_DATA_PENDING = "INVITED_LEASE_DATA_PENDING",
	PAYMENT_DETAIL_PENDING = "PAYMENT_DETAIL_PENDING"
}

export enum PackagePaymentByEnum {
	SELF = "SELF",
	OTHER = "OTHER"
}
export enum DocTypeEnum {
	REFDOC = "REFDOC",
	MASTER = "MASTER"
}

export enum PaymentTypeCodeEnum {
	FLEX = "FLEX",
	DC = "DC",
	CC = "CC",
	CHEQUE = "CHEQUE",
	MO = "MO",
	OTHER = "OTHER"
}
export enum ReceiptStatusEnum {
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	REQUESTED = "REQUESTED"
}

export enum MonthlyProofStatusEnum {
	"ACTIVE" = "ACTIVE",
	"INACTIVE" = "INACTIVE",
	"TERMINATED" = "TERMINATED",
	"REJECTED" = "REJECTED",
	"EXPIRED" = "EXPIRED",
	"REQUESTED" = "REQUESTED",
	"APPROVED" = "APPROVED",
	"LEASE_PENDING" = "LEASE_PENDING",
	"UPLOAD_PENDING" = "UPLOAD_PENDING",
	"DATA_FETCH_PENDING" = "DATA_FETCH_PENDING",
	"LOOKBACK_DATE_FETCH_PENDING" = "LOOKBACK_DATE_FETCH_PENDING",
	"DATA_NOT_FOUND" = "DATA_NOT_FOUND",
	NEWLY_UPLOADED = "NEWLY_UPLOADED",
	REUPLOADED = "REUPLOADED",
	PARTIALLY_APPROVED = "PARTIALLY_APPROVED",
	APPROVAL_PENDING = "APPROVAL_PENDING",
	QUALIFIED = "QUALIFIED"
}

export enum VerifiedProofStatusEnum {
	APPROVED = "APPROVED",
	REJECTED_AFTER_APPROVAL = "REJECTED_AFTER_APPROVAL"
}

export enum PlaidMonthlyProofStatusEnum {
	NEW = "NEW",
	CRYREMP_QUALIFIED = "CRYREMP_QUALIFIED",
	APPROVAL_PENDING = "APPROVAL_PENDING",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED"
}

export enum RefdocOverallStatusEnum {
	PAYMENT_OPTIONS_UPLOAD_PENDING = "PAYMENT_OPTIONS_UPLOAD_PENDING",
	PAYMENT_OPTIONS_APPROVAL_PENDING = "PAYMENT_OPTIONS_APPROVAL_PENDING",
	MONTHLY_PROOFS_UPLOAD_PENDING = "MONTHLY_PROOFS_UPLOAD_PENDING",
	MONTHLY_PROOFS_APPROVAL_PENDING = "MONTHLY_PROOFS_APPROVAL_PENDING",
	APPROVED = "APPROVED"
}

export enum YNStatusEnum {
	YES = "Y",
	NO = "N"
}

export enum DisplayYesNoEnum {
	YES = "Yes",
	NO = "No"
}
export enum AppTypeEnum {
	MOBILE = "MOBILE",
	WEB = "WEB"
}
